### ISSUE TITLE
Mirror - 基于 issues 的博客工具

### ISSUE THREAD

**Issue by LoeiFy** [LoeiFy/Recordum#11]
Mirror 是一个简单的博客工具，基于 GitHub API 获取 issues 数据，然后展示在页面上

该工具的方便之处在于只需要在 issue 上写你的博客文章，你的网站会自动更新博客内容

借助 GitHub，你可以轻松的用 markdown 书写你的博客内容，永久保存，不用担心数据丢失问题。还可以非常方便上传博客图片，拖入编辑器即可。

该博客工具非常适合以 issue 作为自己博客的用户，无痛生成博客网站，对原来内容毫无影响

Mirror 还支持多用户协作，你可以方便的设置哪些用户写的内容可以显示在博客网站上，避免无关内容

Mirror 在移动端同时有很好的浏览体验

## 预览地址

http://mirror.am0200.com/

## 项目地址

https://github.com/LoeiFy/Mirror

新版本使用 GitHub [GraphQL](https://developer.github.com/v4/) API

`REST API` 版本：https://github.com/LoeiFy/Mirror/tree/rest-api

更详细的介绍可以看项目说明

## 如何使用

使用很简单，你可以直接下载资源包，下载最新的 release，然后打开 `index.html` 进行配置即可。

[中文教程](https://github.com/LoeiFy/Mirror/wiki/%E4%B8%AD%E6%96%87%E6%95%99%E7%A8%8B)

配置好后，可以先尝试本地预览，需要一个本地服务器，放上去访问 `index.html` 即可，测试没问题就可以把全部文件上传到对应地址即可，也可以放到 GitHub pages 上

## 名字来源

`Mirror` 是 `DJ Okawari` 所作的专辑

![mirror](https://cloud.githubusercontent.com/assets/2193211/12321915/c66d8b12-baeb-11e5-9612-b188f5272e3b.jpg)

**Comment by nareix** [comment]
想法超赞

**Comment by houhai** [comment]
你好 很喜欢guo.lu的主题风格 在网上搜集以后 有各种版本 但是有各种各样的问题 想问下是否能发送一份主题给我 万分感谢  不会做乱七八糟的事情 自己用来研究和写个人日志  499339376@qq.com  谢谢

**Comment by LoeiFy** [comment]
@houhai 你等待一段时间，迟点我会弄一个完整版本

或者可以看这个版本
https://github.com/LoeiFy/Diaspora/tree/rc

**Comment by houhai** [comment]
@LoeiFy  十分期待完整版本 希望出来的时候百忙之中能告知一下 一直在期待！

**Comment by realooooo** [comment]
期待完整版本。

**Comment by JokerQyou** [comment]
想法很棒，但是 access token 暴露在网页上不会造成安全问题吗？

**Comment by LoeiFy** [comment]
@JokerQyou 这个 token 是只读权限，没有其他任何权限

**Comment by chlinp** [comment]
确实很赞，同期待ing

**Comment by ghost** [comment]
请问issue这个域名怎么解析绑定到github..

**Comment by LoeiFy** [comment]
@ichenss 

https://github.com/LoeiFy/Mirror 这个项目绑定的域名，然后这个项目引入 issues 内容

**Comment by ghost** [comment]
你好@这个域名也是同样和hexo解析嘛？
@        A        192.30.252.153
@        A        192.30.252.154
www      CNAME    username.github.io.

**Comment by insme** [comment]
@LoeiFy 可否发一份 完整版的给我么？很喜欢 Mirror  这套版，还有的这个能架设在 阿里云 之类的 主机上吗？感谢

**Comment by LoeiFy** [comment]
@insme 
https://github.com/LoeiFy/Mirror

直接使用 GitHub pages 来弄就行

**Comment by Mosiki** [comment]
# 好厉害

**Comment by wangzc92** [comment]
很棒，支持

**Comment by wxiubin** [comment]
您好，请问下

```
# token
# token 需要用 `#` 符号分割
# 例子: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
```
用 `#` 号分割是什么意思呢？ 5又是代表什么呢？

**Comment by LoeiFy** [comment]
@sanyucz 那是你在 github 上拿到的 token，按照说明取得你的 token，然后用 '#' 号分割，因为不分割上传到 GitHub 上会被 github 删除的

**Comment by wxiubin** [comment]
可是即便按照格式分割，照样会被删除：https://github.com/sanyucz/blog/blob/gh-pages/config.yml

**Comment by LoeiFy** [comment]
@sanyucz 你应该分割成 `e#ae8ce1ad35dbea85247a78dd395567f2e7b9f8d` 而不是在前面加 `5#`

意思是将你的 token 随便中间插入一个 `#` 字符

**Comment by wxiubin** [comment]
好吧，现在Github不会删除我的token了~
但是问题回来了，控制台log：
```
(index):1 Uncaught ReferenceError: $config is not defined
    at (index):1
(anonymous) @ (index):1
build.f431db64.js:1 Uncaught TypeError: Cannot read property 'token' of undefined
    at Object.<anonymous> (build.f431db64.js:1)
    at t (build.f431db64.js:1)
    at Object.<anonymous> (build.f431db64.js:1)
    at t (build.f431db64.js:1)
    at Object.<anonymous> (build.f431db64.js:1)
    at t (build.f431db64.js:1)
    at Object.<anonymous> (build.f431db64.js:1)
    at t (build.f431db64.js:1)
    at build.f431db64.js:1
    at build.f431db64.js:1
```
config.yml：[https://github.com/sanyucz/blog/blob/gh-pages/config.yml](https://github.com/sanyucz/blog/blob/gh-pages/config.yml)
site:[http://blog.iosgg.cn/](http://blog.iosgg.cn/)

**Comment by LoeiFy** [comment]
@sanyucz 请运行 `mirror build`，然后再提交你的文件

**Comment by wxiubin** [comment]
非常感谢您的帮助！

**Comment by willhunger** [comment]
'''
/usr/local/lib/node_modules/Mirror/node_modules/yamljs/lib/Parser.js:270
        throw new ParseException('Unable to parse.', this.getRealCurrentLineNb() + 1, this.currentLine);
        ^
Error: Unable to parse.
'''
运行mirror build时唔知为什么这样？

**Comment by LoeiFy** [comment]
@willhunger 这个错误是 yml to json 出错了。你检查一下你的 `config.yml` 文件，可能内容格式错了，或者你贴一下你的配置内容

**Comment by willhunger** [comment]
# site title
title:Will's Bolg

# github user
user:willhunger

# issue repository
repository:Blog

# multi-author
authors:willhunger

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token:

# posts per page
perpage:10

**Comment by willhunger** [comment]
@LoeiFy token我去掉了，可是应该没什么错误吧

**Comment by LoeiFy** [comment]
@willhunger 因为你的配置 yml 格式错误，正确格式是 `字段名: 字段值`，注意冒号后面有一个空格。

正确应该为

```yml
# site title
title: Will's Bolg

# github user
user: willhunger

# issue repository
repository: Blog

# multi-author
authors: willhunger

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token:

# posts per page
perpage: 10
```

**Comment by heytxz** [comment]
```
/usr/local/lib/node_modules/Mirror/bin/mirror.js:60
.action((folder = '') => {
                ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
```
您好，请问这是遇到了什么问题？

**Comment by heytxz** [comment]
通过第二种方式搞定了博客…… 从 Hexo 转移了…… 但标题为啥显示不全啊……

<img width="620" alt="2017-08-14 12 03 48" src="https://user-images.githubusercontent.com/9845703/29257975-abd09d84-80e8-11e7-8136-55b2af8eb458.png">

**Comment by LoeiFy** [comment]
@heytxz 第一个问题是你的 nodejs 版本问题，第二个问题是标题太长，首页 css 做隐藏了，没有做换行

**Comment by heytxz** [comment]
@LoeiFy 谢谢。我会更新 nodejs 再试试的！

**Comment by heytxz** [comment]
@LoeiFy 请问我想将底部声明放在其他地方，为了美观不放在底部，LoeiFy 你介意么？

**Comment by LoeiFy** [comment]
@heytxz 无所谓，你可以自行修改

**Comment by heytxz** [comment]
@LoeiFy 谢谢！还是要冒昧问下：**怎么不显示 Label？** 
因为我发现浏览器调窄，标题反而显示全了，应该是 Label 挡住标题的缘故。我之前想问你又住口了… 自己又去试了试，关于 `label` 的语句太多了，实在不知道怎么弄。我只能看懂最简单的代码，这样嵌套深的实在不懂，冒昧求助！ 

我试着将 `n.labelsNum = 3` 改为 `n.labelsNum = 0`，虽然不显示了，但还是占据了空间。

**Comment by heytxz** [comment]
@LoeiFy 我又仔细考虑了下，如果不显示标签，页面就不规则了，也不好看！所以我放弃这样做。多谢。

请问有 Twitter 或者微博么？我想关注。

**Comment by LoeiFy** [comment]
@heytxz `labels` 会根据页面宽度隐藏，同时在非手机页面上显示起到平衡视觉作用

**Comment by heytxz** [comment]
@LoeiFy 平衡视觉的效果确实不错，给个赞！

**Comment by isecret** [comment]
Flower Dance！

**Comment by marsxxl** [comment]
按照步骤来的，请问这样的错误是什么原因呢
Something Error
Error: Request failed with status code 401

**Comment by LoeiFy** [comment]
@xinxiaoliang 401 一般是 token 错误，注意 token 的获取以及记得用 "#" 号分割 token，可以参考这个 issue https://github.com/LoeiFy/Mirror/issues/31

**Comment by marsxxl** [comment]
@LoeiFy token格式是OK的，特意看了下，加了"#"，就是我建完token，github好像自己就删掉了

**Comment by LoeiFy** [comment]
@xinxiaoliang 之所以要加上 ‘#’ 字符分割，是因为如果不做处理上传这个 token 的话会被 GitHub 删除的，所以要分割，然后程序处理成原来的 token

**Comment by marsxxl** [comment]
@LoeiFy 谢谢，我再试一下

**Comment by hjh142857** [comment]
似乎有一些小问题，PC上IE无限小圈圈（Chrome可以打开），安卓UC上也是TAT超喜欢这个主题啊

**Comment by LoeiFy** [comment]
@hjh142857 

uc 的问题已经修复

低版本 ie 问题比较麻烦，主要是跨域问题比较麻烦，所以忽略了

**Comment by wuzehv** [comment]
厉害了，必须试试

**Comment by wuzehv** [comment]
@LoeiFy  作者你好，想问下你是怎么做sitemap的，好像生成不了唉，用的这个网站https://www.xml-sitemaps.com/。  或者你有什么方法能让google抓取博客吗？

**Comment by LoeiFy** [comment]
@wuzehv 看这个 https://acyort.com

**Comment by JeffKko** [comment]
作者你好
我照著步驟做完了
但為什麼進 [http://kko.tw.com](http://kko.tw.com) 都404
[https://github.com/JeffKko/blog/tree/gh-pages](https://github.com/JeffKko/blog/tree/gh-pages)

**Comment by LoeiFy** [comment]
@JeffKko 域名绑定错误，你绑了 cname 了吗？具体自己查一下 `gh-pages 域名绑定`

**Comment by JeffKko** [comment]
了解了～～ 感謝！！

**Comment by wuzehv** [comment]
@LoeiFy  作者你好，根据你之前给的提示，用这个项目https://acyort.com没有seo的问题，现在已经可以正常用了， 但是有个问题就是我fork了你的项目，对主题就行了修改，不知道这样是否允许？  地址：http://wuzehui.top

**Comment by LoeiFy** [comment]
@wuzehv 可以的

**Comment by wuzehv** [comment]
ok， 十分感谢

**Comment by zakokun** [comment]
**想法很强，非常好用的博客工具，感谢博主的辛勤劳作**

**Comment by RockYuan** [comment]
感谢您的付出
能否移植https://github.com/LoeiFy/Mirror到gitee ?
gitee里也有API https://gitee.com/api/v5/swagger#/
会遇到什么困难吗?

**Comment by Salomens** [comment]
很好用的工具

**Comment by ghost** [comment]
```
<script>
window.config = {
  organization: false, // 默认是 false，如果你的项目是属于 GitHub 组织 的，请设置为 true
  order: 'UPDATED_AT', // 文章排序，以 创建时间 或者 更新时间，可选值 'UPDATED_AT'，'CREATED_AT'
  title: 'Mirror', // 博客标题
  user: 'LoeiFy', // GitHub 用户名，必须
  repository: 'Recordum', // GitHub 项目名，指定文章内容来源 issues，必须
  authors: 'LoeiFy,author1', // 博客作者，以 ',' 分割，GitHub 用户名默认包含在内
  ignores: '17,13', // 文章忽略的 issues ID
  host: '', // 博客的主域名，不填自动获取，请注意这个值会影响 hash 的值
  hash: '', // 必须
  perpage: 5, // 分页
}
</script>
```

为啥，我配置了 文章忽略的 issues ID ， 但是，前端还是可以看到文章呢？
